[package]
org = "ballerina"
name = "ai.eval"
version = "0.9.0"
authors = ["Ballerina"]
keywords = ["ai", "evaluation", "llm-as-a-judge", "agent"]
repository = "https://github.com/ballerina-platform/module-ballerina-ai.eval"
license = ["Apache-2.0"]
distribution = "2201.13.4"

[platform.java21]
graalvmCompatible = true
